name: Docker Image CI

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: windows-2019

    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Set output variables
        id: vars
        run: |
          echo "DOCKER_TAG=$('${{ github.ref_name }}' -replace '^v', '' -replace '\.\w+$', '')" >> $env:GITHUB_OUTPUT

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag ababak/cgcpp:${{ steps.vars.outputs.DOCKER_TAG }}

      - name: Push
        run: docker push ababak/cgcpp:${{ steps.vars.outputs.DOCKER_TAG }}
